logging:
  config:
    classpath: logback-spring.xml
    level:
      fr:
        rewrite:
          server: INFO
      org.apache.tomcat.util.net: DEBUG
      org.springframework.boot.web.embedded.tomcat: DEBUG
      org.springframework.boot.ssl: DEBUG

spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: RewriteServer
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  task:
    execution:
      pool:
        core-size: 2
        max-size: 10
        queue-capacity: 100
      thread-name-prefix: async-task-
  jackson:
    default-property-inclusion: non_absent

  ssl:
    bundle:
      pem:
        client1_cert:
          keystore:
            certificate: 'classpath:certs/clients/client1/client1.crt'
            private-key: 'classpath:certs/clients/client1/client1.key'
            private-key-password: 'changeit'
      jks:
        server_cert:
          key:
            alias: 'server_cert'
          keystore:
            location: 'classpath:certs/server/server.p12'
            password: 'changeit'
            type: 'PKCS12'
          truststore:
            location: 'classpath:certs/server/server_truststore.jks'
            password: 'changeit'
            type: 'JKS'

server:
  port: 8080
  ssl:
    enabled: false
  #    client-auth: NEED
  #    bundle: server_cert
  compression:
    enabled: true
    mime-types: text/xml, text/html, textx/css, application/javascript, application/json
    min-response-size: 1024

rewrite:
  server:
    config-directory: /home/cedric/rewrite/config
    work-directory: /home/cedric/rewrite/repository
    mvn-path: /home/cedric/.sdkman/candidates/maven/current/bin/mvn
    datastore:
      cache-directory: .datastore
      repository-directory: project

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    access:
      default: none
    jmx:
      exposure:
        exclude: '*'
    web:
      base-path: /management
      exposure:
        include:
          - configprops
          - env
          - health
          - info
          - logfile
          - loggers
          - threaddump
  info:
    env:
      enabled: true
    # Git Information
    git:
      enabled: true
      mode: full

developer:
  mode: false
