logging:
  config:
    classpath: logback-spring.xml
    level:
      fr:
        rewrite:
          back: INFO
spring:
  application:
    name: RewriteBack
  data:
    redis:
      database: 0
      url: redis://localhost:6379
  jackson:
    default-property-inclusion: non_absent
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:certs/server/server.p12
    key-store-type: PKCS12
    key-store-password: changeit
    key-alias: server_cert
    trust-store: classpath:certs/server/server_truststore.jks
    trust-store-type: JKS
    trust-store-password: changeit
    client-auth: NEED # Exige un certificat client valide

rewrite:
  server:
    work-directory: /tmp/rewrite-server-work # Sur Linux/macOS
    # Ou sur Windows : work-directory: C:\Temp\rewrite-server-work
