logging:
  config:
    classpath: logback-spring.xml
    level:
      fr:
        rewrite:
          server: INFO

spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: RewriteServer
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  task:
    execution:
      pool:
        core-size: 2
        max-size: 10
        queue-capacity: 100
      thread-name-prefix: async-task-
  jackson:
    default-property-inclusion: non_absent
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      poolName: Hikari
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/rewriteServer
    username: rewriteServer
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        jdbc:
          batch_size: 25
          time_zone: UTC
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:certs/server/server.p12
    key-store-type: PKCS12
    key-store-password: changeit
    key-alias: server_cert
    trust-store: classpath:certs/server/server_truststore.jks
    trust-store-type: JKS
    trust-store-password: changeit
    client-auth: NEED

org:
  jobrunr:
    job-scheduler:
      enabled: true

    background-job-server:
      enabled: true
      worker-count: 4
    dashboard:
      enabled: false
      port: 8000
    database:
      type: sql

rewrite:
  server:
    config: /home/cedric/rewrite/config
    work: /home/cedric/rewrite/repository
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    access:
      default: none
    jmx:
      exposure:
        exclude: '*'
    web:
      base-path: /management
      exposure:
        include:
          - configprops
          - env
          - health
          - info
          - logfile
          - loggers
          - threaddump
  info:
    env:
      enabled: true
    # Git Information
    git:
      enabled: true
      mode: full
