GET {{host}}:{{port}}/management
###
GET {{host}}:{{port}}/management/beans
###
GET {{host}}:{{port}}/management/caches
###
GET {{host}}:{{port}}/management/health
###
GET {{host}}:{{port}}/management/info
###
GET {{host}}:{{port}}/management/env
###
GET {{host}}:{{port}}/management/loggers
###
GET {{host}}:{{port}}/management/heapdump
###
GET {{host}}:{{port}}/management/threaddump
###
GET {{host}}:{{port}}/management/metrics