// test valide
POST https://{{host}}/api/rewrite/datastore
Content-Type: application/json

{ "url" : "https://github.com/antarus/jhipster-lite" }
###
// test invalide
POST https://{{host}}/api/rewrite/datastore
Content-Type: application/json

{  }
###

GET https://{{host}}/api/rewrite/datastore/904d1170-4bd7-3324-8139-95115b43bbe4
###

GET https://{{host}}/api/rewrite/datastore/904d1170-4bd7-3324-8139-95115b43bbef
