POST {{host}}:{{port}}/api/repository/clone
Content-Type: application/json

{
 "datastoreId": {
   "uuid": "904d1170-4bd7-3324-8139-95115b43bbe4"
 },
  "url" : "github.com/antarus/jhipster-lite",
"credential": {
  "username": {{ github.username }},
  "pat": {{ github.pat }}
}
}

###

DELETE {{host}}:{{port}}/api/repository/delete
Content-Type: application/json

{
 "datastoreId": {
   "uuid": "904d1170-4bd7-3324-8139-95115b43bbe4"
 }
}

###

POST {{host}}:{{port}}/api/repository/branch
Content-Type: application/json

{
  "datastoreId": {
    "uuid": "904d1170-4bd7-3324-8139-95115b43bbe4"
  },
  "name": "feat/test"
}
